package expo.modules.notificationmotion.money

// Generated by scripts/generate-money-widget-resources.mjs. Do not edit.

import expo.modules.notificationmotion.R

/**
 * One background bill. Sizes are multiples of the bill unit; velocities are in the bill's own
 * size per second; [spin] is degrees per second around the frame's center (orbit only), at
 * [radius] times the half width. [phase] spreads the bills along their paths.
 */
internal class AmbientSlot(
  val size: Float,
  val alpha: Float,
  /** The bill's resting tilt, in degrees. */
  val rotation: Float,
  val vx: Float,
  val vy: Float,
  val spin: Float,
  val radius: Float,
  val phase: Float,
)

internal object MoneyEffects {
  /** The bill unit the layouts are drawn at, in dp. */
  const val UNIT = 36f
  /** When the flying bills land and the digits start rolling, in ms into the frame. */
  const val IMPACT = 440
  val slots: Map<String, List<AmbientSlot>> = mapOf(
    "rain" to listOf(
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -3f, vx = -0.01f, vy = 0.55f, spin = 0f, radius = 0f, phase = 0.345f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 10f, vx = -0.021f, vy = 0.75f, spin = 0f, radius = 0f, phase = 0.584f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 2f, vx = 0.029f, vy = 1f, spin = 0f, radius = 0f, phase = 0.788f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -10f, vx = -0.005f, vy = 0.55f, spin = 0f, radius = 0f, phase = 0.442f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 5f, vx = -0.053f, vy = 0.75f, spin = 0f, radius = 0f, phase = 0.914f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = -20f, vx = 0.031f, vy = 1f, spin = 0f, radius = 0f, phase = 0.338f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 15f, vx = -0.059f, vy = 0.55f, spin = 0f, radius = 0f, phase = 0.771f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 23f, vx = -0.028f, vy = 0.75f, spin = 0f, radius = 0f, phase = 0.712f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 0f, vx = -0.044f, vy = 1f, spin = 0f, radius = 0f, phase = 0.196f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 26f, vx = 0.06f, vy = 0.55f, spin = 0f, radius = 0f, phase = 0.512f),
    ),
    "stream" to listOf(
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 14f, vx = 0.6f, vy = 0.021f, spin = 0f, radius = 0f, phase = 0.733f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = -8f, vx = 0.8f, vy = 0.044f, spin = 0f, radius = 0f, phase = 0.966f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 18f, vx = 1.05f, vy = 0.049f, spin = 0f, radius = 0f, phase = 0.125f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -25f, vx = 0.6f, vy = -0.046f, spin = 0f, radius = 0f, phase = 0.964f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 0f, vx = 0.8f, vy = -0.039f, spin = 0f, radius = 0f, phase = 0.999f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 19f, vx = 1.05f, vy = -0.024f, spin = 0f, radius = 0f, phase = 0.472f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 6f, vx = 0.6f, vy = -0.043f, spin = 0f, radius = 0f, phase = 0.606f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = -10f, vx = 0.8f, vy = 0.036f, spin = 0f, radius = 0f, phase = 0.295f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 2f, vx = 1.05f, vy = 0.004f, spin = 0f, radius = 0f, phase = 0.041f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -30f, vx = 0.6f, vy = -0.042f, spin = 0f, radius = 0f, phase = 0.636f),
    ),
    "fountain" to listOf(
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -18f, vx = 0.057f, vy = -0.55f, spin = 0f, radius = 0f, phase = 0.857f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 8f, vx = -0.059f, vy = -0.75f, spin = 0f, radius = 0f, phase = 0.422f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 29f, vx = -0.021f, vy = -1f, spin = 0f, radius = 0f, phase = 0.028f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -13f, vx = 0.031f, vy = -0.55f, spin = 0f, radius = 0f, phase = 0.266f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 2f, vx = 0.078f, vy = -0.75f, spin = 0f, radius = 0f, phase = 0.048f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 21f, vx = -0.029f, vy = -1f, spin = 0f, radius = 0f, phase = 0.751f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 28f, vx = 0.076f, vy = -0.55f, spin = 0f, radius = 0f, phase = 0.203f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = -11f, vx = 0.028f, vy = -0.75f, spin = 0f, radius = 0f, phase = 0.584f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = 27f, vx = -0.033f, vy = -1f, spin = 0f, radius = 0f, phase = 0.096f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 2f, vx = 0.041f, vy = -0.55f, spin = 0f, radius = 0f, phase = 0.659f),
    ),
    "orbit" to listOf(
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -11f, vx = 0f, vy = 0f, spin = 24f, radius = 0.5f, phase = 0.378f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 13f, vx = 0f, vy = 0f, spin = 25f, radius = 0.65f, phase = 0.522f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = -23f, vx = 0f, vy = 0f, spin = -30f, radius = 0.8f, phase = 0.33f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = -21f, vx = 0f, vy = 0f, spin = 25f, radius = 0.5f, phase = 0.493f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 13f, vx = 0f, vy = 0f, spin = 36f, radius = 0.65f, phase = 0.562f),
      AmbientSlot(size = 1f, alpha = 1f, rotation = -27f, vx = 0f, vy = 0f, spin = -33f, radius = 0.8f, phase = 0.026f),
      AmbientSlot(size = 0.62f, alpha = 0.5f, rotation = 5f, vx = 0f, vy = 0f, spin = 32f, radius = 0.5f, phase = 0.096f),
      AmbientSlot(size = 0.8f, alpha = 0.78f, rotation = 28f, vx = 0f, vy = 0f, spin = 28f, radius = 0.65f, phase = 0.074f),
    ),
  )
}

/** One aurora blob: [baseX]/[baseY] are fractions of the half width/height from the center;
 * it drifts along [dirX]/[dirY] by ±[amplitude] of its [size] (dp), taking [leg] seconds each way. */
internal class AuroraBlob(
  val size: Float,
  val baseX: Float,
  val baseY: Float,
  val dirX: Float,
  val dirY: Float,
  val amplitude: Float,
  val leg: Float,
  val phase: Float,
  val deep: Boolean,
)

internal object MoneyAurora {
  val blobs = listOf(
    AuroraBlob(size = 260f, baseX = -0.55f, baseY = -0.7f, dirX = 0.9f, dirY = 0.44f, amplitude = 0.14f, leg = 7f, phase = 0f, deep = false),
    AuroraBlob(size = 220f, baseX = 0.62f, baseY = 0.62f, dirX = -0.86f, dirY = -0.5f, amplitude = 0.14f, leg = 8f, phase = 0.37f, deep = true),
    AuroraBlob(size = 180f, baseX = 0.05f, baseY = 0.05f, dirX = 0.8f, dirY = -0.6f, amplitude = 0.12f, leg = 11f, phase = 0.71f, deep = false),
  )
  /** Each blob's containers by direction (forward, back) and pulse (none, cents, whole). */
  val containers: List<List<IntArray>> = listOf(
    listOf(intArrayOf(R.id.nmw_au0fn, R.id.nmw_au0fc, R.id.nmw_au0fw), intArrayOf(R.id.nmw_au0bn, R.id.nmw_au0bc, R.id.nmw_au0bw)),
    listOf(intArrayOf(R.id.nmw_au1fn, R.id.nmw_au1fc, R.id.nmw_au1fw), intArrayOf(R.id.nmw_au1bn, R.id.nmw_au1bc, R.id.nmw_au1bw)),
    listOf(intArrayOf(R.id.nmw_au2fn, R.id.nmw_au2fc, R.id.nmw_au2fw), intArrayOf(R.id.nmw_au2bn, R.id.nmw_au2bc, R.id.nmw_au2bw)),
  )
  val images: List<List<IntArray>> = listOf(
    listOf(intArrayOf(R.id.nmw_aui0fn, R.id.nmw_aui0fc, R.id.nmw_aui0fw), intArrayOf(R.id.nmw_aui0bn, R.id.nmw_aui0bc, R.id.nmw_aui0bw)),
    listOf(intArrayOf(R.id.nmw_aui1fn, R.id.nmw_aui1fc, R.id.nmw_aui1fw), intArrayOf(R.id.nmw_aui1bn, R.id.nmw_aui1bc, R.id.nmw_aui1bw)),
    listOf(intArrayOf(R.id.nmw_aui2fn, R.id.nmw_aui2fc, R.id.nmw_aui2fw), intArrayOf(R.id.nmw_aui2bn, R.id.nmw_aui2bc, R.id.nmw_aui2bw)),
  )
}
