/** @type {import('expo/fingerprint').Config} */
const config = {
    sourceSkips: [
        // The default skip.
        "PackageJsonAndroidAndIosScriptsIfNotContainRun",
        // semantic-release bumps `version` on every release. The binary can run any later
        // JS, so a version bump alone mustn't change the runtime version and lock out updates.
        "ExpoConfigVersions",
    ],
    // Generated by prebuild and gitignored, so EAS never sees them. Hashing a local copy
    // would make an update published from this machine miss the builds it targets.
    ignorePaths: ["android/**/*", "ios/**/*"],
    extraSources: [
        // Bun applies these patches to native modules, but the fingerprint only looks for a
        // root `patches` folder, so a native patch change wouldn't change the runtime version.
        { type: "dir", filePath: "src/patches", reasons: ["bunPatchedDependencies"] },
        // Decides which native libraries use RNRepo's prebuilt binaries or build from source.
        { type: "file", filePath: "rnrepo.config.json", reasons: ["rnrepoConfig"] },
    ],
};

module.exports = config;
